import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { sqliteD1 } from './sqlite-d1.mjs';
import { initializeCommunity } from './community.mjs';
import { defaultSeason } from './season.mjs';
import { isoWeekValue, dateFromWeek, competitionData, publicDifficulty } from './community-core.mjs';

test('Semaines ISO, dates imprécises et moyenne des seuls avis publics',()=>{
 assert.equal(isoWeekValue('2026-12-31'),'2026-W53');assert.equal(dateFromWeek('2026-W53'),'2026-12-28');
 assert.equal(dateFromWeek('2027-W01'),'2027-01-04');assert.throws(()=>dateFromWeek('2027-W53'));
 assert.deepEqual(competitionData({title:'Meeting',weekStart:'2026-10-04'}),{title:'Meeting',weekStart:'2026-09-28',date:null,location:'',level:''});
 assert.equal(competitionData({title:'Meeting',date:'2029-09-08'}).weekStart,'2029-09-03');
 assert.throws(()=>competitionData({title:'Meeting',date:'2026-02-30'}));
 assert.deepEqual(publicDifficulty([{rating:4,isPrivate:false},{rating:2,isPrivate:false},{rating:1,isPrivate:true},{rating:null,isPrivate:false}]),{count:2,average:3});
});

test('API Cloudflare : migration sans perte, mots de passe, confidentialité et compétitions partagées',async t=>{
 const native=new DatabaseSync(':memory:');t.after(()=>native.close());const DB=sqliteD1(native);
 // Realistic previous D1 schema: accounts without a password field and content already edited.
 native.exec(`CREATE TABLE users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,name TEXT NOT NULL,role TEXT NOT NULL,profile TEXT NOT NULL DEFAULT '{}',profile_version INTEGER NOT NULL DEFAULT 1,last_name TEXT NOT NULL DEFAULT '',phone TEXT NOT NULL DEFAULT '',account_version INTEGER NOT NULL DEFAULT 1,previous_role TEXT NOT NULL DEFAULT 'athlete');
 CREATE TABLE auth(token TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires INTEGER NOT NULL);
 CREATE TABLE records(collection TEXT NOT NULL,id TEXT NOT NULL,data TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1,archived INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(collection,id));
 CREATE TABLE meta(key TEXT PRIMARY KEY,value INTEGER NOT NULL);
 CREATE TABLE role_events(id INTEGER PRIMARY KEY,actor TEXT NOT NULL,member TEXT NOT NULL,previous_role TEXT NOT NULL,next_role TEXT NOT NULL,created INTEGER NOT NULL);
 INSERT INTO meta VALUES ('seeded',1),('revision',12),('setup_complete',1),('last_session_cleanup',0);`);
 for(const [id,role] of [['alice','athlete'],['bob','athlete'],['coach','coach'],['maylis','admin']])native.prepare('INSERT INTO users(id,email,name,role,profile,profile_version,last_name,phone) VALUES(?,?,?,?,?,?,?,?)').run(id,id,id,role,JSON.stringify({times:{200:id==='alice'?24:28}}),7,'Nom','0600000000');
 const season=structuredClone(defaultSeason);season.trainingPeriods[0].label='Période déjà modifiée';season.competitions=[{week:5,label:'Meeting déjà ajouté'}];
 const oldSession={id:'ancien',title:'Séance conservée',date:'2024-01-02',type:'speed',targets:[],workout:'Texte personnalisé'};
 const oldCompetition={id:'ancienne-competition',title:'Ancien meeting',date:'2026-10-03',type:'competition',targets:[]};
 for(const [collection,item,archived] of [['sessions',oldSession,0],['sessions',oldCompetition,0],['season',{...season,id:'2026-2027'},0],['info',{id:'info',title:'Info éditée',body:'Texte déjà présent',category:'organisation'},0],['sessions',{...oldSession,id:'archive'},1]])native.prepare('INSERT INTO records(collection,id,data,version,archived) VALUES(?,?,?,?,?)').run(collection,item.id,JSON.stringify(item),9,archived);
 const usersBefore=native.prepare('SELECT * FROM users ORDER BY id').all(),recordsBefore=native.prepare('SELECT * FROM records ORDER BY collection,id').all();
 // Use the production Pages handler; only adapt its JSON import for Node's module loader.
 const url=new URL('./functions/api/[[path]].js',import.meta.url);
 const code=readFileSync(url,'utf8').replace("import seed from '../../seed.json';",`const seed=${readFileSync(new URL('./seed.json',import.meta.url),'utf8')};`).replace(/from '\.\.\/\.\.\/([^']+)'/g,(_,path)=>`from '${new URL(path,import.meta.url).href}'`);
 const {onRequest}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
 const request=async(path,method='GET',body,session)=>{
  const response=await onRequest({env:{DB},request:new Request('https://equipe.test/api'+path,{method,headers:{'Content-Type':'application/json',...(session?{Authorization:'Bearer '+session.accessToken}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})})});
  return {status:response.status,json:await response.json()};
 };
 assert.equal((await request('/auth')).status,200);
 assert.deepEqual(native.prepare('SELECT * FROM users ORDER BY id').all(),usersBefore);
 for(const original of recordsBefore)assert.deepEqual(native.prepare('SELECT * FROM records WHERE collection=? AND id=?').get(original.collection,original.id),original);
 assert.equal(native.prepare("SELECT COUNT(*) AS n FROM records WHERE collection='sessions'").get().n,3,'No 90-day cleanup or reseeding');
 const login=async id=>{const result=await request('/login','POST',{email:id,password:id});assert.equal(result.status,200,JSON.stringify(result.json));return result.json;};
 const alice=await login('alice'),bob=await login('bob'),coach=await login('coach'),owner=await login('maylis');
 assert.equal((await request('/login','POST',{email:'Alice',password:'alice'})).status,401);
 assert.equal((await request('/login','POST',{email:'alice',password:'Alice'})).status,401);
 const state=async who=>(await request('/state','GET',undefined,who)).json;
 const original=await state(alice);
 assert.deepEqual(original.profile.times,{200:24});assert.equal(original.profileVersion,7);assert.equal(original.passwordProvisional,true);
 assert.equal(original.competitions.length,2);assert.equal(original.competitions.find(c=>c.id==='legacy-season-0').date,null);
 assert.equal(original.sessions.some(s=>s.id==='ancien'),true);
 assert.equal(JSON.stringify(original).includes('password_hash'),false);assert.equal(JSON.stringify(original).includes('initial_identifier'),false);
 assert.equal((await request('/password','PUT',{password:'A',version:original.passwordVersion},alice)).status,200);
 assert.equal((await request('/password','PUT',{password:'B',version:original.passwordVersion},alice)).status,409);
 assert.equal((await request('/login','POST',{email:'alice',password:'alice'})).status,401);
 assert.equal((await request('/login','POST',{email:'alice',password:'a'})).status,401);
 assert.equal((await request('/login','POST',{email:'alice',password:'A'})).status,200);
 const storedHash=native.prepare('SELECT password_hash FROM account_credentials WHERE user_id=?').get('alice').password_hash;
 assert.ok(storedHash.startsWith('pbkdf2:'));assert.notEqual(storedHash,'A');
 await initializeCommunity(DB);
 assert.equal(native.prepare('SELECT password_hash FROM account_credentials WHERE user_id=?').get('alice').password_hash,storedHash,'Migration cannot reset an existing password');
 assert.deepEqual(native.prepare('SELECT * FROM users ORDER BY id').all(),usersBefore);
 const caseAccount=await request('/register','POST',{email:'Alice',password:' Z ',name:'Autre Alice'});assert.equal(caseAccount.status,201);
 assert.equal((await request('/register','POST',{email:'Alice',password:'x',name:'Doublon'})).status,409);
 assert.equal((await request('/login','POST',{email:'Alice',password:'Z'})).status,401);
 assert.equal((await request('/login','POST',{email:'Alice',password:' Z '})).status,200);
 assert.equal((await request('/account','PUT',{email:'Alice',name:'alice',version:1},alice)).status,409);
 assert.equal((await request('/account','PUT',{email:'ALICE',name:'Alice',version:1},alice)).status,200);
 assert.equal((await request('/login','POST',{email:'ALICE',password:'A'})).status,200);
 assert.deepEqual((await state(alice)).profile.times,{200:24});
 const comment=(who,rating,body,isPrivate,version)=>request('/sessions/ancien/comment','PUT',{rating,body,isPrivate,version},who);
 assert.equal((await comment(alice,null,'',false,0)).status,400);assert.equal((await comment(alice,6,'',false,0)).status,400);
 assert.equal((await comment(alice,4,'Avis public',false,0)).status,200);
 assert.equal((await comment(bob,1,'Retour privé',true,0)).status,200);
 assert.equal((await state(bob)).comments.length,2);
 for(const who of [alice,owner,caseAccount.json]){const s=await state(who);assert.equal(s.comments.length,1);assert.equal(JSON.stringify(s).includes('Retour privé'),false);}
 const coachState=await state(coach);assert.equal(coachState.comments.length,2);assert.deepEqual(publicDifficulty(coachState.comments),{count:1,average:4});
 assert.equal((await comment(bob,2,'Retour devenu public',false,1)).status,200);
 assert.equal((await comment(bob,5,'Ancienne version',false,1)).status,409);
 assert.deepEqual(publicDifficulty((await state(alice)).comments),{count:2,average:3});
 assert.equal((await request('/sessions/ancien/comment','DELETE',{version:1,userId:'alice'},bob)).status,409,'Only the authenticated member can affect their own comment');
 assert.equal((await request('/sessions/ancien/comment','DELETE',{version:1},alice)).status,200);
 assert.deepEqual(publicDifficulty((await state(coach)).comments),{count:1,average:2});
 const future={title:'Séance future',date:'2029-09-03',type:'speed',targets:[]};
 const createdSession=(await request('/sessions','POST',future,coach)).json;
 assert.equal((await request('/sessions/'+createdSession.id+'/comment','PUT',{rating:null,body:'Texte sans vote',isPrivate:false,version:0},alice)).status,200);
 assert.equal((await request('/sessions/ancien','DELETE',{version:9},alice)).status,403);
 assert.equal((await request('/season','PUT',original.season,alice)).status,403);
 const legacy=original.competitions.find(c=>c.id==='legacy-season-0');
 const precise={...legacy,date:'2026-10-02',location:'Paris',level:'regional',title:'Meeting complété par Bob'};
 assert.equal((await request('/competitions/'+legacy.id,'PUT',precise,bob)).status,200);
 assert.equal((await request('/competitions/'+legacy.id,'PUT',precise,owner)).status,409);
 assert.deepEqual(native.prepare("SELECT data FROM records WHERE collection='season'").get().data,recordsBefore.find(r=>r.collection==='season').data,'Competition editing must not overwrite season periods');
 const weekOnly=await request('/competitions','POST',{title:'Autre compétition de la semaine',weekStart:'2026-09-28'},alice);assert.equal(weekOnly.status,201);
 const beyond=await request('/competitions','POST',{title:'Meeting 2029',date:'2029-09-08',location:'Stade'},owner);assert.equal(beyond.status,201);
 assert.equal((await request('/competitions','POST',{title:'Date invalide',date:'2026-02-30'},alice)).status,400);
 for(const who of [alice,coach,owner])assert.equal((await request('/competitions/'+legacy.id+'/signup','PUT',{registered:true,userId:'bob'},who)).status,200);
 assert.equal((await request('/competitions/'+legacy.id+'/signup','PUT',{registered:true},alice)).status,200);
 const registrations=(await state(bob)).signups.filter(s=>s.competitionId===legacy.id);assert.equal(registrations.length,3);assert.equal(registrations.some(s=>s.userId==='bob'),false);
 assert.deepEqual(new Set(registrations.map(s=>s.role)),new Set(['athlete','coach','admin']));
 assert.equal((await request('/competitions/'+legacy.id+'/signup','PUT',{registered:false},coach)).status,200);
 assert.equal((await state(bob)).signups.filter(s=>s.competitionId===legacy.id).length,2);
 assert.equal((await request('/competitions/'+weekOnly.json.id,'DELETE',{version:1},bob)).status,200,'Anyone can remove another member’s competition');
 await initializeCommunity(DB);assert.equal((await state(bob)).competitions.some(c=>c.id===weekOnly.json.id),false,'Restart cannot resurrect an archived competition');
 const after=await state(bob);assert.equal(after.competitions.find(c=>c.id===legacy.id).title,precise.title);assert.equal(after.competitions.some(c=>c.id===beyond.json.id),true);
 assert.equal((await request('/account','DELETE',{identifier:'ALICE',confirm:true},alice)).status,200);
 assert.equal((await state(bob)).signups.some(s=>s.userId==='alice'),false);assert.equal((await state(coach)).comments.some(c=>c.userId==='alice'),false);
 assert.equal(native.prepare('SELECT COUNT(*) AS n FROM account_credentials WHERE user_id=?').get('alice').n,0);
 assert.equal((await state(coach)).sessions.some(s=>s.id==='ancien'),true);
 // Admin account management never changes shared training or another member's times.
 assert.equal((await state(owner)).members.find(m=>m.id==='bob').createdAt,null);
 const fresh=(await state(owner)).members.find(m=>m.id===caseAccount.json.user.id);
 assert.ok(fresh.createdAt>Date.now()-60000);assert.equal(fresh.email,'Alice');
 assert.equal((await state(bob)).members.some(m=>'email' in m),false);
 const memberPath='/members/'+fresh.id;
 for(const who of [bob,coach]){
  assert.equal((await request(memberPath+'/password','PUT',{version:1},who)).status,403);
  assert.equal((await request(memberPath+'/coach','PUT',{version:1,action:'grant-coach'},who)).status,403);
  assert.equal((await request(memberPath,'DELETE',{version:1,identifier:'Alice',confirm:true},who)).status,403);
 }
 assert.equal((await request(memberPath+'/coach','PUT',{version:1,action:'grant-coach'},owner)).status,200);
 assert.equal((await state(caseAccount.json)).user.role,'coach');
 assert.equal((await request(memberPath+'/password','PUT',{version:1},owner)).status,409);
 assert.equal((await request(memberPath+'/coach','PUT',{version:2,action:'revoke-coach'},owner)).status,200);
 assert.equal((await state(caseAccount.json)).user.role,'athlete');
 assert.equal((await request(memberPath+'/password','PUT',{version:3,password:''},owner)).status,400);
 const reset=await request(memberPath+'/password','PUT',{version:3,password:'Choisi'},owner);assert.equal(reset.status,200);assert.equal(reset.json.temporaryPassword,'Choisi');
 assert.equal((await request('/state','GET',undefined,caseAccount.json)).status,401);
 assert.equal((await request('/login','POST',{email:'Alice',password:' Z '})).status,401);
 assert.equal((await request('/login','POST',{email:'Alice',password:'choisi'})).status,401);
 const renewed=(await request('/login','POST',{email:'Alice',password:'Choisi'})).json;
 const renewedState=await state(renewed);assert.equal(renewedState.passwordProvisional,true);
 assert.equal((await comment(renewed,3,'À effacer avec le compte',false,0)).status,200);
 await request('/competitions/'+legacy.id+'/signup','PUT',{registered:true},renewed);
 assert.equal((await request(memberPath,'DELETE',{version:4,identifier:'alice',confirm:true},owner)).status,400);
 assert.equal((await request(memberPath,'DELETE',{version:4,identifier:'Alice',confirm:true},owner)).status,200);
 assert.equal((await request('/state','GET',undefined,renewed)).status,401);
 for(const table of ['account_created','account_credentials','session_comments','competition_signups','auth'])assert.equal(native.prepare(`SELECT COUNT(*) AS n FROM ${table} WHERE user_id=?`).get(fresh.id).n,0);
 assert.equal((await state(owner)).competitions.some(c=>c.id===legacy.id),true);
 assert.deepEqual((await state(bob)).profile.times,{200:28});
 assert.equal((await request('/members/maylis','DELETE',{version:1,identifier:'maylis',confirm:true},owner)).status,409);
 const successor=(await request('/register','POST',{email:'Successeur',password:'x',name:'Admin temporaire'})).json;
 assert.equal((await request('/members/'+successor.user.id+'/admin','PUT',{action:'grant-admin',expectedRole:'athlete'},owner)).status,200);
 assert.equal((await request('/members/'+successor.user.id,'DELETE',{version:2,identifier:'Successeur',confirm:true},owner)).status,200,'An admin can delete another admin while retaining a successor');
 assert.equal((await state(owner)).members.filter(m=>m.role==='admin').length,1);
 await initializeCommunity(DB);assert.equal((await state(owner)).members.find(m=>m.id==='bob').createdAt,null,'Restart cannot invent historic registration dates');
});
