export const library = [
  ['acronym','SaS','Salutation au Soleil (×1 ou 2 selon préférence)'],
  ['acronym','JF','Jane Fonda (chaque mouvement ×8 si pas de consigne précise)'],
  ['acronym','CD','Copenhaguen dynamique'],
  ['acronym','MB','Medecine Ball'],
  ['circuit','Circuit Charléty','Prisonner squat / Burpees / Superman\nFente arrière alternée / Mountain Climber / gainage\nBicyclette / Ciseaux / V-ups alternés\n\nChaque exercice dure 30 s — 1 minute de récupération tous les 3 exercices — 2 min entre deux circuits.'],
  ['circuit','Circuit Paris','Accordéon / roulade hurdler / Gainage militaire\nGood Morning / pompe / Extension cheville\nRelevé de bassin / Superman / Jumping jack\n\nChaque exercice dure 30 s — 1 minute de récupération tous les 3 exercices — 2 min entre deux circuits.'],
  ['circuit','Circuit Montsouris','Anges des neiges (ventre) / Dead Bug / Ange des neiges (dos)\nStarzynski / pompes / fente latéral / fente latéral\nAbdo jambes tendues alterné / Extension dos / good morning\n\nChaque exercice dure 30 s — 1 minute de récupération tous les 3 exercices — 2 min entre deux circuits.'],
  ['circuit','Circuit Gammes','Marche A — Marche fente — Marche étirement dynamique des ischios — Marche arrière — A-skip — Pas chassé ×2 — fente dynamique — course arrière — Montée de genoux — Jambes tendues\n\nGammes sur 30 m (sauf marche arrière sur 20 m), retour trotté — Bras actifs !'],
  ['circuit','Circuit 4 + 4','4 exercices — 30 s d’effort / 30 s de récupération + 400 m (~1 min 10 à 1 min 20 pour les gars / ~1 min 30 à 1 min 40 pour les filles), 3 min de récup tous les 3.\nExercices au choix dans la liste « Exercices circuits ».'],
  ['circuit','Circuit 4 + 1','4 exercices — 30 s d’effort / 30 s de récupération + 100 m (H : 15/16 niveau N et IR1 vers 16/17 ; F : 18/19 pour N et IR1 vers 20/21).\nExercices au choix dans la liste « Exercices circuits ».'],
  ['circuit','Exercices circuits','A-skip / B-skip / Marche A / Jambes tendues / Montée de genoux / talon fesse / Dribble / pas chassés / carioca / fente dynamique / course arrière / Squat du prisonnier / Good morning / jumping jack / burpees / Mountain Climber / Accordéon / Pompes / V-sit / V sit croisé / Fente arrière / Deadbug / Ciseau / Cossack / Roulade Hurdler']
].map(([category,title,body],i)=>({id:`library-${i}`,category,title,body,version:1}));

export const info = [
 ['organisation','🏃☀️','Les stages de la saison',`J'organiserai deux stages, le premier à Noël dans la salle indoor de Saint-Brieuc du 19 au 23 décembre. Je lancerai l'organisation courant octobre. Le deuxième aura lieu pendant les vacances de printemps parisienne (probablement la première semaine du 3 au 10 avril) dans le sud, je pense au Portugal ou en Espagne.`],
 ['organisation','🏋️','Accès à la musculation',`Pour les entrainements de musculation : Selon le nombre de personne régulière je devrais limiter le nombre de présent à partir d'octobre. La priorité se fera sur l'ancienneté puis le niveau. Je m'excuse de procéder comme cela mais le matériel disponible et la taille de la salle rend très difficile la pratique pour un groupe de plus de 15 athlètes. Si certains décident de prendre un abonnement à la salle, je ferai en sorte que tous les exercices soit maîtrisé avant de vous laisser en autonomie, ou j'adapterai les séances.`],
 ['organisation','🗓️','Rattraper la séance du samedi',`Si vous ne pouvez pas venir à l'entraînement du samedi matin et que vous souhaitez rattraper la séance, privilégiez (sauf contre indication de ma part) le vendredi ou le samedi après-midi. La séance du lundi sera souvent celle de sprint et nécessite plus de fraîcheur nerveuse. Cela permet aussi d'avoir une vraie coupure mentale et physique avant le début de chaque semaine.`],
 ['organisation','☝️','Créneaux du midi',`Je proposerai régulièrement les séances du lundi et du jeudi soir sur le créneau du midi ou début d'après-midi le même jour. Je vous informerai chaque semaine car ce ne sera pas à chaque fois mais si vous êtes disponible cela permet des séances plus qualitative en petit groupe. Pour le moment ce serait sur la piste annexe.`],
 ['relationnel','🐆','Engagement et performance',`Je considère que j'entraîne un groupe de compétition et de performance, peu importe le niveau de performance que vous visez. Un podium au championnat de France ou simplement vous améliorer sur le 400m ou le 400m haies. Ca veut dire qu'il y a un minimum de sérieux à avoir à l'entrainement, à l'écoute des consignes, dans l'attitude et aussi dans l'état de forme avec lequel vous arrivez à l'entrainement. Ca ne veut pas dire que votre vie doit tourner autour de l'athlé (au contraire !!!) mais que vous respectiez le degré d'engagement que vous mettez dans l'athlétisme. (Ce qui veut aussi dire se reposer si besoin !!!)`],
 ['relationnel','🌴','Absences, douleurs et adaptation',`Si vous ne venez pas à un entrainement, ou que vous arrêtez un exercice ou une séance en cours de route, vous n'êtes pas obligé de me prévenir ! si il y a une douleur ou un problème lié à l'entrainement c'est mieux que je le sache, mais je vous fais confiance par principe et libre à vous de m'en parler (j'essaye d'être à l'écoute). Si un exercice en particulier vous fait mal, vous gêne ou autres, n'hésitez pas à me le dire et j'essaierai d'en trouver un similaire (dans la limite de l'individualisation).`],
 ['relationnel','🩸','Adapter pendant les règles',`Vous êtes trop nombreuse pour que je prenne en compte les règles dans l'entrainement, si ça tombe pendant une séance 'importante' et que ça vous limite voire vous empêche de la faire, reposez vous et vous la rattraperai plus tard.`],
 ['relationnel','👯🏻','Attention et relations dans le groupe',`J'essaye au mieux de donner une attention similaire à chaque athlète (à investissement égal) à l'entrainement et en compétition, dans le suivi, les conseils etc... en revanche j'aurais forcément des relations interpersonnelle différentes avec chacun d'entre vous, que ce soit par affinité naturelle, ancienneté, moment partagé etc... si vous trouvez que ça fait une différence entre certains dans le cadre de l'entrainement n'hésitez pas à m'en parler !`],
 ['relationnel','☎️','Contacter le coach',`Pour le contact je privilégie Whatsapp et les SMS. Je vous demanderai aussi de me contacter le moins possible après 21h30 et le dimanche (sauf période de compétition). En tant que coach notre vie tourne beaucoup autour de l'athlé et comme pour vous c'est important de couper.`],
 ['relationnel','🕑','L’équilibre hors de la piste',`De manière similaire, ça peut m'arriver de partir de l'entrainement 10 à 20 minutes plus tôt comme jeudi dernier pour voir des amis, je le fais rarement (pas plus d'une ou deux fois par mois) mais c'est nécessaire pour garder ses amis moldus (non-athlète).`],
 ['relationnel','⚠️','À qui parler en cas de problème',`Si vous avez un problème dans le groupe, et que je suis concerné de près ou de loin ou que vous ne souhaitez pas m'en parler, vous pouvez vous adresser à Isak au 07 68 83 78 93 (directeur technique de la section) ou Delphine semondes.dechelette@gmail.com (la présidente).`],
 ['relationnel','🤍','Respect et entraide',`Evidemment pas d'insulte, pas d'harcèlement, encouragez vous, prenez soin des autres. Vous n'êtes pas obligé d'être tous amis en dehors de la piste, vous aurez évidemment chacun vos affinités et vous pouvez même ne pas vous apprécier mais ça n'empêche pas de se soutenir à l'entrainement et en compétition.`]
].map(([category,icon,title,body],i)=>({id:`info-${i}`,category,icon,title,body,version:1}));
